#!/bin/bash
####################################################################
####################################################################
####################################################################
############CODE FLOW IS STARTING BELOW THESE COMMENTS##############
####################################################################
####################################################################
####This script is aimed to obtain the QC statistics for a BAM/CRAM
####file.
####The pipeline executed for either a BAM or CRAM is very similar,
####the only difference is represented by the presence of a command
####able to convert a CRAM to a BAM. Once the BAM is obtained the very
####same pipeline is executed for the two file types.
####
####The script is executed by the parent
####            QC/Scripts/start.sh
####that passes the following arguments to this script
####
####    currentDir--->  current working directory from where the parent script was executed
####    fileDir--->     folder where to store the outputs generated by this QC pipeline
####    fileName--->    base name of the BAM/CRAM file under analysis
####    filePath--->    full path for the BAM/CRAM file under analysis
####    KeyFile--->     path to the file storing the encryption key to be used to encrypt some of the QC pipeline outputs
####    typeFile--->    inferred file type for the BAM/CRAM file under consideration
currentDir=$1; #KK
fileDir=$2; #output
fileName=$3; #used but fixed
fileName='xxxxx'
filePath=$4; #KK
pipeErrorFolder=$5;
KeyFile=$6;
typeFile=$7

######################################################################################
###########Paths to the tools used in this pipeline###################################
######################################################################################
######################################################################################
sam_tool_command="/homes/angel/samtoolsINST-1.3.1-EBI-comp-RH6.3/bin/samtools";
sam_tool_command="samtools";
picardToolsCommand="/homes/angel/picard-2.8.2.jar";
picardToolsCommand="/usr/local/picard.jar";
bedToolsCommand="bamToFastq";
#bedToolsCommand2="bedtools";
#bgzipCommand="/homes/angel/samtoolsINST-1.3.1-EBI-comp-RH6.3/bin/bgzip";
FastqcCommand="$currentDir/PipelineScripts/FastQC/fastqc";
FastqcCommand="/usr/local/FastQC/fastqc";
######################################################################################
######################################################################################


######################################################################################
############Printing the above tools version to a file################################
######################################################################################
SWversions="$fileDir/SW_versions"       ###file where to store the versions of the tools used in this pipeline
> $SWversions
echo "$sam_tool_command;$($sam_tool_command --version 2>&1)" >> $SWversions
echo "$picardToolsCommand;$(java -jar $picardToolsCommand ValidateSamFile --version 2>&1)" >> $SWversions
echo "$bedToolsCommand;$($bedToolsCommand -h 2>&1)" >> $SWversions
#echo "$bedToolsCommand2;$($bedToolsCommand2 -h 2>&1)" >> $SWversions
#echo "$bgzipCommand;$($bgzipCommand -h 2>&1)" >> $SWversions
echo "$FastqcCommand;$($FastqcCommand -v 2>&1)" >> $SWversions
######################################################################################
######################################################################################

######################################################################################
###############Additional resouces needed to run the pipeline#########################
######################################################################################
teePath="/homes/angel/coreutils-8.25-INST/bin/tee";
teePath="tee";
#bunzip2Path="/homes/angel/bunzip2";
#MpileupModificationScript="$currentDir/PipelineScripts/MpileupModification.pl";
######################################################################################
######################################################################################


######################################################################################
#Output, standard output and standard error files generated during pipeline execution#
######################################################################################
quickCheckFile="$fileDir/quickCheck.txt";                               quickErr="$pipeErrorFolder/quickcheck.e";
ValidateSamFileSummary="$fileDir/validateSamSummary.txt";               validErr="$pipeErrorFolder/validateSummary.e";
ValidateSamFileProperPairSummary="$fileDir/validateSamProperPairSummary.txt";           validProperPairErr="$pipeErrorFolder/validateProperPairSummary.e";
headerFile="$fileDir/header.txt.openssl.gz";                            headErr="$pipeErrorFolder/header.e";
biopsyFile="$fileDir/biopsy.openssl";                                   biopsyErr="$pipeErrorFolder/biopsy.e";
statFile="$fileDir/stats.txt.openssl.gz";                                  statErr="$pipeErrorFolder/stats.e";
fastqFile="$fileDir/$fileName.fq";                                      errorForBAMtoFASTQ="$pipeErrorFolder/reducedBAMtoFASTQ.e";
FastqcOutFile="$pipeErrorFolder/fastqc.o";                              errorForFASTQC="$pipeErrorFolder/fastqc.e";
MappedStatFile="$fileDir/MappedStats.txt";                              MappedStatError="$pipeErrorFolder/MappedStats.e";
UnmappedStatFile="$fileDir/UnmappedStats.txt";                          UnmappedStatError="$pipeErrorFolder/UnmappedStats.e";
#ModifiedMpileupFile="$fileDir/CoverageCompressed.mpileup.gz";          mpileErr="$pipeErrorFolder/mpileup.e";
MQFile="$fileDir/MappingQuality.txt";                                   mqErr="$pipeErrorFolder/mappingQuality.e";
errorUnzip="$pipeErrorFolder/unzip.e";
#ModifiedMpileupFileEncrypted="$fileDir/CoverageCompressed.mpileup.gz.openssl"; encErr="$pipeErrorFolder/encryption.e";
IndexFile="$fileDir/out.index";         IndexOut="$pipeErrorFolder/index.o";    IndexErr="$pipeErrorFolder/index.e";
######################################################################################
######################################################################################


if [ "xx${SLURM_CPUS_PER_TASK}xx" == "xxxx" ]; then
        SLURM_CPUS_PER_TASK=100
fi

EncryptionKey=$(sed '1q;d' $KeyFile);   ###encryption key to encrypt some of the generated output
if [ "$typeFile" == "BAM" ] || [ "$typeFile" == "CRAM" ]; then  ###if the inferred file type was equal to BAM or CRAM
        if [ "$typeFile" == "CRAM" ]; then
                sec="$sam_tool_command view -h -b -"
        else
                sec="cat"
        fi
{
        {
                ###The code below is aimed to do the following task:
                ###command to get the standard input, parallelize the process and compute the index for the BAM/CRAM under analysis. Finally, convert the BAM/CRAM to SAM
                ###command to get the 0.01% of the reads contained in the CRAM/BAM and get a FASTQ file on the subset of reads
                ###command to get the number of mapped reads for each available chromosome
                ###command to get the number of unmapped reads for each available chromosome
                ###command to get the number of reads showing a given mapping quality value
                ###command to have a fast check of the basic expected properties on the CRAM/BAM file
                ###command to perform a more deep analysis on the validity of the CRAM/BAM file under analysis
                ###command to get the header from the CRAM/BAM file
                ###command to generate multiple statistics on the CRAM/BAM under analysis
                cat - | $teePath -p >($sam_tool_command index - $IndexFile >$IndexOut 2>$IndexErr) | eval $sec | $teePath -p \
                >(head -c 1M | openssl aes-256-cbc -a -salt -k $EncryptionKey > $biopsyFile 2>$biopsyErr) \
                >(($sam_tool_command stats - | openssl aes-256-cbc -a -salt -k $EncryptionKey | gzip) > $statFile 2>$statErr) \
                >($sam_tool_command view -f 4 - | cut -f3 | sort -T $fileDir | uniq -c | sort -T $fileDir -k1nr | awk 'OFS="\t" {print $2,$1}' > $UnmappedStatFile 2>$UnmappedStatError) \
                >($sam_tool_command view - | cut -f5 | sort -T $fileDir | uniq -c | sort -T $fileDir -k1nr | awk 'OFS="\t" {print $2,$1}' > $MQFile 2>$mqErr) \
                >($sam_tool_command quickcheck -v - > $quickCheckFile 2>$quickErr) \
                >($sam_tool_command view -b -s 0.001 - | $bedToolsCommand -i - -fq $fastqFile 2>$errorForBAMtoFASTQ) \
                >($sam_tool_command view -F 4 - | cut -f3 | sort -T $fileDir | uniq -c | sort -T $fileDir -k1nr | awk 'OFS="\t" {print $2,$1}' > $MappedStatFile 2>$MappedStatError) \
                >($sam_tool_command view -H | openssl aes-256-cbc -a -salt -k $EncryptionKey | gzip > $headerFile 2>$headErr) \
                >($sam_tool_command view -h        - | sed '/^[^@]/s/\tMC\:i\:-*[0-9]*\t/\t/' | java -Xmx$((SLURM_CPUS_PER_TASK*3900))m -Djava.io.tmpdir=$fileDir -jar $picardToolsCommand ValidateSamFile I=/dev/stdin O=$ValidateSamFileSummary MODE=SUMMARY IGNORE_WARNINGS=TRUE 2>$validErr) \
                > /dev/null

#-Xmx1500g = limit so big, that effectively becomes no limit
#now mem

#https://www.biostars.org/p/370966/
#1/7/2022 exclude MC:i as obsolete and not following specification

# just properly paired
#               >($sam_tool_command view -h -f 0x2 - | sed '/^[^@]/s/\tMC\:i\:-*[0-9]*\t/\t/' | java -Djava.io.tmpdir=$fileDir -jar $picardToolsCommand ValidateSamFile I=/dev/stdin O=$ValidateSamFileProperPairSummary MODE=SUMMARY IGNORE_WARNINGS=TRUE 2>$validProperPairErr) \

                #################################################################################################
                ###### Command to calculate the mpileup and modify it to get a much more compact version ########
                ##>($sam_tool_command mpileup -d 10000 -A -q 0 -Q 0 --output-MQ - | awk '{print $1,$2,$2,$4,$5,$6,$7}' OFS='\t' | $bedToolsCommand2 merge -c 4,5,6,7 -o collapse -delim "  " 2>$mpileErr | perl $MpileupModificationScript | $bgzipCommand | openssl aes-256-cbc -a -salt -k $EncryptionKey > $ModifiedMpileupFileEncrypted 2>$encErr) \
                #################################################################################################
                #################################################################################################
        } 3>&1 >&4 4>&- | cat;
} 4>&1
fi

#################################################################################
########## Code to execute FASTQC on the FASTQ file obtained      ###############
########## considering the 0.0% of the reads in the CRAM/BAM file ###############
#################################################################################
fastq_mem="$((SLURM_CPUS_PER_TASK*3900))"
fastq_mem_under_9000="$((fastq_mem<9000 ? fastq_mem : 9000))"
$FastqcCommand $fastqFile -o $fileDir -f fastq --memory $fastq_mem_under_9000 > $FastqcOutFile 2>$errorForFASTQC        ###command to execute FASTQC
suffix="_fastqc";                                                                       ###suffix for the FASTQC execution output
fastqcZip="$fileDir/$fileName$suffix.zip";                                              ###zip file resulting from FASTQC execution
fastqcHtml="$fileDir/$fileName$suffix.html";                                            ###html file resulting from FASTQC execution
unzip $fastqcZip -d $fileDir 1>/dev/null 2>$errorUnzip;                                 ###command to uncompress the obtained zip file
#################################################################################
#################################################################################

#################################################################################
######### Code to parse the FASTQC output to retrieve ###########################
######### the used base calling encodying system      ###########################
#################################################################################
FastqcFolder="$fileDir/$fileName$suffix";                       ###folder where are located the outputs generated by FASTQC execution
if [ -d $FastqcFolder ]; then                                   ###if the folder exists it means that the output was properly generated and un-compressed
        dataFile="$FastqcFolder/fastqc_data.txt";               ###output file storing the data of interest
        Encoding=$(grep "Encoding" $dataFile | cut -f 2);       ###retrieved base calling encodying system
        QualEncodeFile="$fileDir/EncodingQual.txt";             ###file where to store the retrieved base calling encoded system
        echo $Encoding > $QualEncodeFile;                       ###command to print the retrieved encodying system to the file above
        rm -r $FastqcFolder;                                    ###command to remove the output of FASTQC execution
fi;

if [ -f $fastqFile ]; then                                      ###if the specific FASTQC output file was generated
        rm $fastqFile;                                          ###command to remove FASTQC exeuction output file
fi;
if [ -f $fastqcZip ]; then                                      ###if the specific FASTQC output file was generated
        rm $fastqcZip;                                          ###command to remove FASTQC exeuction output file
fi;
if [ -f $fastqcHtml ]; then                                     ###if the specific FASTQC output file was generated
        rm $fastqcHtml;                                         ###command to remove FASTQC exeuction output file
fi;
#################################################################################
#################################################################################